YES = 'да'
NO = 'нет'
HACK = 'рубить'
PRICK = 'колоть'
SHOOT = 'стрелять'
MAGIC = 'колдовать'
ENDURANCE = 'прочность'
HERO = 'герой'
INVENTARY = 'инв'
WEAPON = 'оружие'
INVENTARY_WEAPON_MESSAGE = (f'Для смены оружия введите {WEAPON}. '
                            f'Для продолжения введите {YES}')
WHAT_DOING = 'Что будем делать? '
MAGIC_HEALTH = 'Сколько жизненных сил вы готовы вложить в колдовство? '
